name: "drewish"
description: "eating my own dog food"
author: "andrew morton"

# Where things are
source:       .
destination:  ./_site
plugins_dir:  ./_plugins
layouts_dir:  ./_layouts
# data_dir:     ./_data
includes_dir: ./_includes
# collections:  null

# Handling Reading
safe:         false
include:      [".htaccess"]
exclude:      ['README.md', 'Rakefile', 'Gemfile', 'Gemfile.lock', 'Guardfile']
keep_files:   [".git", ".svn"]
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Filtering Content
# show_drafts: false
# limit_posts: 0
# future:      false
# unpublished: false

# Plugins
plugins:
- jekyll-paginate
- jekyll_oembed
- jekyll-resize

# Conversion
markdown:    kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"
incremental: false

# Outputting
permalink:     "/:year/:month/:day/:title/"
paginate_path: "/blog/page-:num/"
paginate:      20
timezone:      null

quiet:    false
defaults: []

# Serving
url:     https://drewish.com
baseurl: "" # does not include hostname

redcarpet:
  extensions: [smart, fenced_code_blocks, autolink, strikethrough]

