name: "drewish"
description: "eating my own dog food"
author: "andrew morton"

source:      .
destination: ./_site
plugins_dir: ./_plugins
layouts_dir: ./_layouts
include:     ['.htaccess']
exclude:     ['README.md', 'Rakefile', 'Gemfile', 'Gemfile.lock', 'Guardfile']
keep_files:  ['.git','.svn']
timezone:    nil

future:      true
show_drafts: false
limit_posts: 0
highlighter: true

permalink:     '/:year/:month/:day/:title'
paginate:      20
paginate_path: '/blog/page-:num'

markdown:      redcarpet
markdown_ext:  markdown,mkd,mkdn,md
textile_ext:   textile

encoding: utf-8
excerpt_separator: "\n\n"

safe:        false
host:        0.0.0.0
port:        80
baseurl:     /
url:         http://drewish.com
lsi:         false

gems:
- jekyll-assets
- jekyll-paginate

redcarpet:
  extensions: [smart, fenced_code_blocks, autolink, strikethrough]

redcloth:
  hard_breaks: true
