name: "drewish"
description: "eating my own dog food"
author: "andrew morton"

source:      .
destination: ./_site
plugins:     ./_plugins
layouts:     ./_layouts
include:     ['.htaccess']
exclude:     ['README.md', 'Rakefile', 'Gemfile', 'Gemfile.lock']
keep_files:  ['.git','.svn']
timezone:    nil

future:      true
show_drafts: false
limit_posts: 0
pygments:    true

relative_permalinks: true

permalink:     '/:year/:month/:day/:title'
paginate:      20
paginate_path: '/blog/page-:num'

markdown:      redcarpet
markdown_ext:  markdown,mkd,mkdn,md
textile_ext:   textile

excerpt_separator: "\n\n"

safe:        false
host:        0.0.0.0
port:        4000
baseurl:     /
url:         http://localhost:4000
lsi:         false

redcarpet:
  extensions: [smart, fenced_code_blocks, autolink, strikethrough]

redcloth:
  hard_breaks: true
